[build] 
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.75.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.75.1" 

[context.deploy-preview.environment]
  HUGO_VERSION = "0.75.1"
<<<<<<< HEAD
  
  
=======
>>>>>>> dc0c3cce8a98e079d84cf176d588915c5717638f
